DROP TABLE IF EXISTS CARE_RECORD;
CREATE TABLE CARE_RECORD(
    `ID` INTEGER NOT NULL  DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_08BB762A_1999_457A_B173_57F8AD06D92C) COMMENT '主键id' ,
    `CUS_WORKID` INTEGER NOT NULL   COMMENT '所属机构id' ,
    `SENDSTAFF_ID` INTEGER NOT NULL   COMMENT '发送职员id' ,
    `RECEIVECUS_ID` INTEGER NOT NULL   COMMENT '接收用户id' ,
    `SEND_STATUS` INTEGER NOT NULL   COMMENT '发送状态' ,
    `SEND_WAY` VARCHAR(255) NOT NULL   COMMENT '发送方式' ,
    `SEND_CONTENT` VARCHAR(255) NOT NULL   COMMENT '发送内容' ,
    `IS_VALID` INTEGER NOT NULL   COMMENT '是否有效' ,
    `BEGIN_TIME` TIMESTAMP NOT NULL   COMMENT '创建时间' ,
    `CHANGE_TIME` TIMESTAMP NOT NULL   COMMENT '修改时间' ,
    `DELETE_TIME` TIMESTAMP NOT NULL   COMMENT '删除时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '';


CREATE UNIQUE INDEX PRIMARY_KEY_AD ON CARE_RECORD(ID);

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER(
    `ID` INTEGER NOT NULL  DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_954EC815_4981_41A0_B614_75F734DEA21D) COMMENT '' ,
    `CUS_ACCOUNT` VARCHAR(255) NOT NULL   COMMENT '账号' ,
    `CUS_NAME` VARCHAR(255) NOT NULL   COMMENT '用户名' ,
    `CUS_PASSWORD` VARCHAR(255) NOT NULL   COMMENT '密码' ,
    `CUS_ID` INTEGER NOT NULL   COMMENT '角色id' ,
    `CUS_WORKID` INTEGER NOT NULL   COMMENT '所属机构id' ,
    `CUS_EMAIL` VARCHAR(255) NOT NULL   COMMENT '邮箱' ,
    `CUS_PHONE` VARCHAR(255) NOT NULL   COMMENT '手机号' ,
    `CUS_BIRTH` TIMESTAMP NOT NULL   COMMENT '生日' ,
    `CUS_ADDRESS` VARCHAR(255) NOT NULL   COMMENT '住址' ,
    `IS_VALID` INTEGER NOT NULL   COMMENT '是否有效' ,
    `BEGIN_TIME` TIMESTAMP NOT NULL   COMMENT '创建时间' ,
    `CHANGE_TIME` TIMESTAMP NOT NULL   COMMENT '修改时间' ,
    `DELETE_TIME` TIMESTAMP NOT NULL   COMMENT '删除时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '';


CREATE UNIQUE INDEX PRIMARY_KEY_5 ON CUSTOMER(ID);

DROP TABLE IF EXISTS CUSTOMER_INFO;
CREATE TABLE CUSTOMER_INFO(
    `ID` INTEGER NOT NULL  DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_50DCD054_9D6B_421D_982E_53F78357FC62) COMMENT '主键id' ,
    `CUS_ID` INTEGER NOT NULL   COMMENT '用户id' ,
    `RECOMMEND_ID` INTEGER NOT NULL   COMMENT '推荐职员id' ,
    `CUS_RESOURCE` VARCHAR(255) NOT NULL   COMMENT '客户来源' ,
    `DUE` TIMESTAMP NOT NULL   COMMENT '预产期' ,
    `NEED_TIME` TIMESTAMP NOT NULL   COMMENT '需求日期' ,
    `NEED_CONTENT` VARCHAR(255) NOT NULL   COMMENT '需求内容' ,
    `EXPECT_CITY` VARCHAR(255) NOT NULL   COMMENT '期望城市' ,
    `IS_OLDUSER` INTEGER NOT NULL   COMMENT '是否为老用户' ,
    `IS_VALID` INTEGER NOT NULL   COMMENT '是否有效' ,
    `BEGIN_TIME` TIMESTAMP NOT NULL   COMMENT '创建时间' ,
    `CHANGE_TIME` TIMESTAMP NOT NULL   COMMENT '修改时间' ,
    `DELETE_TIME` TIMESTAMP NOT NULL   COMMENT '删除时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '';


CREATE UNIQUE INDEX PRIMARY_KEY_3 ON CUSTOMER_INFO(ID);

DROP TABLE IF EXISTS CUST_FOLLOW_RECORD;
CREATE TABLE CUST_FOLLOW_RECORD(
    `ID` INTEGER NOT NULL  DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_CECC371A_57AF_4A10_80E5_6E0F7B556B82) COMMENT '主键id' ,
    `CUS_WORKID` INTEGER NOT NULL   COMMENT '所属机构id' ,
    `CUS_ID` INTEGER NOT NULL   COMMENT '客户id' ,
    `FOLLOWSTAFF_ID` INTEGER NOT NULL   COMMENT '跟进职员id' ,
    `CUS_RELATIONSHIP` VARCHAR(255) NOT NULL   COMMENT '与客户关系' ,
    `COMMUNICATION_CONTENT` VARCHAR(255) NOT NULL   COMMENT '沟通内容' ,
    `FOLLOW_TIME` TIMESTAMP NOT NULL   COMMENT '跟进日期' ,
    `IS_VALID` INTEGER NOT NULL   COMMENT '是否有效' ,
    `BEGIN_TIME` TIMESTAMP NOT NULL   COMMENT '创建时间' ,
    `CHANGE_TIME` TIMESTAMP NOT NULL   COMMENT '修改时间' ,
    `DELETE_TIME` TIMESTAMP NOT NULL   COMMENT '删除时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '';


CREATE UNIQUE INDEX PRIMARY_KEY_3B ON CUST_FOLLOW_RECORD(ID);

DROP TABLE IF EXISTS JOB;
CREATE TABLE JOB(
    `ID` INTEGER NOT NULL  DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_A1326A90_DF46_4D11_AF2E_863B6B7A7DDA) COMMENT '主键id' ,
    `JOB_NAME` VARCHAR(255) NOT NULL   COMMENT '职位名称' ,
    `IS_VALID` INTEGER NOT NULL   COMMENT '是否有效' ,
    `BEGIN_TIME` TIMESTAMP NOT NULL   COMMENT '创建时间' ,
    `CHANGE_TIME` TIMESTAMP NOT NULL   COMMENT '修改时间' ,
    `DELETE_TIME` TIMESTAMP NOT NULL   COMMENT '删除时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '';


CREATE UNIQUE INDEX PRIMARY_KEY_1 ON JOB(ID);

DROP TABLE IF EXISTS MONEY_SITUATION;
CREATE TABLE MONEY_SITUATION(
    `ID` INTEGER NOT NULL  DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_B74D3F50_B420_457E_A70A_F57494C7E0CB) COMMENT '主键id' ,
    `CUS_WORKID` INTEGER NOT NULL   COMMENT '所属机构id' ,
    `SALESTAFF_ID` INTEGER NOT NULL   COMMENT '销售人员id' ,
    `CONTRACT_ID` INTEGER NOT NULL   COMMENT '服务合同id' ,
    `CUS_ID` INTEGER NOT NULL   COMMENT '客户id' ,
    `COLLECTION_TIME` TIMESTAMP NOT NULL   COMMENT '收款时间' ,
    `CONTRACT_AMOUNT` DECIMAL(5,2) NOT NULL   COMMENT '合同金额' ,
    `PAYMENT_AMOUNT` DECIMAL(5,2) NOT NULL   COMMENT '收款金额' ,
    `BALANCE_AMOUNT` DECIMAL(5,2) NOT NULL   COMMENT '尾款金额' ,
    `IS_VALID` INTEGER NOT NULL   COMMENT '是否有效' ,
    `BEGIN_TIME` TIMESTAMP NOT NULL   COMMENT '创建时间' ,
    `CHANGE_TIME` TIMESTAMP NOT NULL   COMMENT '修改时间' ,
    `DELETE_TIME` TIMESTAMP NOT NULL   COMMENT '删除时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '';


CREATE UNIQUE INDEX PRIMARY_KEY_8 ON MONEY_SITUATION(ID);

DROP TABLE IF EXISTS PROMOTION_RECORD;
CREATE TABLE PROMOTION_RECORD(
    `ID` INTEGER NOT NULL  DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_0B913A36_EB68_4F70_A1D2_E9AC12F80C4A) COMMENT '主键id' ,
    `CUS_WORKID` INTEGER NOT NULL   COMMENT '所属机构id' ,
    `CUS_ID` INTEGER NOT NULL   COMMENT '用户id' ,
    `ORIGINAL_GRADE` VARCHAR(255) NOT NULL   COMMENT '原等级' ,
    `CURRENT_GRADE` VARCHAR(255) NOT NULL   COMMENT '现等级' ,
    `PROMOTION_EVALUATION` VARCHAR(255) NOT NULL   COMMENT '晋升评价' ,
    `PROMOTION_TIME` TIMESTAMP NOT NULL   COMMENT '晋升时间' ,
    `IS_VALID` INTEGER NOT NULL   COMMENT '是否有效' ,
    `BEGIN_TIME` TIMESTAMP NOT NULL   COMMENT '创建时间' ,
    `CHANGE_TIME` TIMESTAMP NOT NULL   COMMENT '修改时间' ,
    `DELETE_TIME` TIMESTAMP NOT NULL   COMMENT '删除时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '';


CREATE UNIQUE INDEX PRIMARY_KEY_33 ON PROMOTION_RECORD(ID);

DROP TABLE IF EXISTS RECEPTION_SITUATION;
CREATE TABLE RECEPTION_SITUATION(
    `ID` INTEGER NOT NULL  DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_CF7ABA6F_12D6_40D6_A9AB_76D7C9CECA0F) COMMENT '主键id' ,
    `CUSTOMER_SERVICE_ID` INTEGER NOT NULL   COMMENT '客服id' ,
    `CUSTOMER_SERVICE_NAME` VARCHAR(255) NOT NULL   COMMENT '客服姓名' ,
    `CUS_PHONE` VARCHAR(255) NOT NULL   COMMENT '联系方式' ,
    `CUS_ADDRESS` VARCHAR(255) NOT NULL   COMMENT '客户住址' ,
    `NEED` VARCHAR(255) NOT NULL   COMMENT '所需需求' ,
    `COMMUNICATION_CONTENT` VARCHAR(255) NOT NULL   COMMENT '沟通内容' ,
    `REQUIRE_TIME` TIMESTAMP NOT NULL   COMMENT '需要时间' ,
    `IS_VALID` INTEGER NOT NULL   COMMENT '是否有效' ,
    `BEGIN_TIME` TIMESTAMP NOT NULL   COMMENT '创建时间' ,
    `CHANGE_TIME` TIMESTAMP NOT NULL   COMMENT '修改时间' ,
    `DELETE_TIME` TIMESTAMP NOT NULL   COMMENT '删除时间' ,
    `FOLLOWSTAFF_ID` INTEGER NOT NULL   COMMENT '跟进职员' ,
    `FOLLOW_SCHEDULE` VARCHAR(255) NOT NULL   COMMENT '跟进进度' ,
    PRIMARY KEY (ID)
)  COMMENT = '';


CREATE UNIQUE INDEX PRIMARY_KEY_F ON RECEPTION_SITUATION(ID);

DROP TABLE IF EXISTS RETURN_VISIT_RECORD;
CREATE TABLE RETURN_VISIT_RECORD(
    `ID` INTEGER NOT NULL  DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_D73EA244_558B_4BC7_9578_72BB6E653901) COMMENT '主键id' ,
    `CUS_WORKID` INTEGER NOT NULL   COMMENT '所属机构id' ,
    `CUS_RETURN_ID` INTEGER NOT NULL   COMMENT '回访用户id' ,
    `INITIATOR_ID` INTEGER NOT NULL   COMMENT '发起者id' ,
    `RETURN_TIME` TIMESTAMP NOT NULL   COMMENT '回访日期' ,
    `COMMUNICATION_CONTENT` VARCHAR(255) NOT NULL   COMMENT '沟通内容' ,
    `CUS_RETURN_TYPE` INTEGER NOT NULL   COMMENT '回访用户类型' ,
    `IS_VALID` INTEGER NOT NULL   COMMENT '是否有效' ,
    `BEGIN_TIME` TIMESTAMP NOT NULL   COMMENT '创建时间' ,
    `CHANGE_TIME` TIMESTAMP NOT NULL   COMMENT '修改时间' ,
    `DELETE_TIME` TIMESTAMP NOT NULL   COMMENT '删除时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '';


CREATE UNIQUE INDEX PRIMARY_KEY_22 ON RETURN_VISIT_RECORD(ID);

DROP TABLE IF EXISTS RIGHT;
CREATE TABLE RIGHT(
    `ID` INTEGER NOT NULL  DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_45EB8413_0E47_4E44_B367_E2D1FF1BC714) COMMENT '主键id' ,
    `UPPER_LEVEL_RESOURCE` INTEGER NOT NULL   COMMENT '上一级资源' ,
    `RESOURCE_URL` VARCHAR(255) NOT NULL   COMMENT '资源url' ,
    `RIGHT_NAME` VARCHAR(255) NOT NULL   COMMENT '权限名称' ,
    `RIGHT_CODE` VARCHAR(255) NOT NULL   COMMENT '权限编码' ,
    `IS_SHOW` INTEGER NOT NULL   COMMENT '是否显示' ,
    `IS_VALID` INTEGER NOT NULL   COMMENT '是否有效' ,
    `BEGIN_TIME` TIMESTAMP NOT NULL   COMMENT '创建时间' ,
    `CHANGE_TIME` TIMESTAMP NOT NULL   COMMENT '修改时间' ,
    `DELETE_TIME` TIMESTAMP NOT NULL   COMMENT '删除时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '';


CREATE UNIQUE INDEX PRIMARY_KEY_4 ON RIGHT(ID);

DROP TABLE IF EXISTS ROLE;
CREATE TABLE ROLE(
    `ID` INTEGER NOT NULL  DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_A5AE4EA9_9FD8_4883_A39C_F1437151D5B7) COMMENT '主键id' ,
    `CUS_WORKID` INTEGER NOT NULL   COMMENT '所属机构id' ,
    `ROLE_CODE` VARCHAR(255) NOT NULL   COMMENT '角色编码' ,
    `ROLE_NAME` VARCHAR(255) NOT NULL   COMMENT '角色名称' ,
    `REMARK` VARCHAR(255) NOT NULL   COMMENT '备注' ,
    `PRIVILEGE_SET` VARCHAR(2550) NOT NULL   COMMENT '权限集合' ,
    `IS_VALID` INTEGER NOT NULL   COMMENT '是否有效' ,
    `BEGIN_TIME` TIMESTAMP NOT NULL   COMMENT '创建时间' ,
    `CHANGE_TIME` TIMESTAMP NOT NULL   COMMENT '修改时间' ,
    `DELETE_TIME` TIMESTAMP NOT NULL   COMMENT '删除时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '';


CREATE UNIQUE INDEX PRIMARY_KEY_26 ON ROLE(ID);

DROP TABLE IF EXISTS SERVICE_CONTRACT;
CREATE TABLE SERVICE_CONTRACT(
    `ID` INTEGER NOT NULL  DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_47CCE57D_CF9A_4241_8FDC_50BDD6032C2D) COMMENT 'id' ,
    `CUS_WORKID` INTEGER NOT NULL   COMMENT '所属机构id' ,
    `SERVICE_TYPEID` INTEGER NOT NULL   COMMENT '服务类型id' ,
    `CUS_ID` INTEGER NOT NULL   COMMENT '客户id' ,
    `BABYSITTER_ID` INTEGER NOT NULL   COMMENT '育婴师id' ,
    `BABYCONSULTANT_ID` INTEGER NOT NULL   COMMENT '育婴顾问id' ,
    `EXP_TIME` TIMESTAMP NOT NULL   COMMENT '预产期' ,
    `SIGN_TIME` TIMESTAMP NOT NULL   COMMENT '预计签约时间' ,
    `SERVICE_BEGIN_TIME` TIMESTAMP NOT NULL   COMMENT '服务开始日期' ,
    `SERVICE_END_TIME` TIMESTAMP NOT NULL   COMMENT '服务结束日期' ,
    `ADDRESS` VARCHAR(255) NOT NULL   COMMENT '住址' ,
    `SERVICE_CONTENT` VARCHAR(255) NOT NULL   COMMENT '服务内容' ,
    `CONTRACT_MONEY` DECIMAL(5,2) NOT NULL   COMMENT '合同金额' ,
    `CONTRACT_STATUS` INTEGER NOT NULL   COMMENT '合同状态' ,
    `STAR` INTEGER NOT NULL   COMMENT '星级' ,
    `SERVICE_EVALUATION` VARCHAR(255) NOT NULL   COMMENT '服务评价' ,
    `IS_VALID` INTEGER NOT NULL   COMMENT '是否有效' ,
    `BEGIN_TIME` TIMESTAMP NOT NULL   COMMENT '创建时间' ,
    `CHANGE_TIME` TIMESTAMP NOT NULL   COMMENT '修改时间' ,
    `DELETE_TIME` TIMESTAMP NOT NULL   COMMENT '删除时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '';


CREATE UNIQUE INDEX PRIMARY_KEY_E ON SERVICE_CONTRACT(ID);

DROP TABLE IF EXISTS SERVICE_TYPE;
CREATE TABLE SERVICE_TYPE(
    `ID` INTEGER NOT NULL  DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_2483AB5F_3C37_4EB0_BA5F_04E740059D51) COMMENT '主键id' ,
    `CUS_WORKID` INTEGER NOT NULL   COMMENT '所属机构id' ,
    `SERVICE_NAME` VARCHAR(255) NOT NULL   COMMENT '服务名称' ,
    `SERVICE_CONTENT` VARCHAR(255) NOT NULL   COMMENT '服务内容' ,
    `CUS_COST` DECIMAL(32) NOT NULL   COMMENT '用户支付费用' ,
    `BABYSITTER_MONEY` DECIMAL(5,2) NOT NULL   COMMENT '育婴师工资' ,
    `BABYCONSULTANT_MONEY` DECIMAL(5,2) NOT NULL   COMMENT '育婴顾问工资' ,
    `BABYSITTER_GRADE` INTEGER NOT NULL   COMMENT '育婴师等级' ,
    `IS_VALID` INTEGER NOT NULL   COMMENT '是否有效' ,
    `BEGIN_TIME` TIMESTAMP NOT NULL   COMMENT '创建时间' ,
    `CHANGE_TIME` TIMESTAMP NOT NULL   COMMENT '修改时间' ,
    `DELETE_TIME` TIMESTAMP NOT NULL   COMMENT '删除时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '';


CREATE UNIQUE INDEX PRIMARY_KEY_A ON SERVICE_TYPE(ID);

DROP TABLE IF EXISTS STAFF_GRADE;
CREATE TABLE STAFF_GRADE(
    `ID` INTEGER NOT NULL  DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_94C37B0F_3614_44FE_8F63_C0494826A1C4) COMMENT '主键id' ,
    `JOB_ID` INTEGER NOT NULL   COMMENT '所属职位' ,
    `CUS_WORKID` INTEGER NOT NULL   COMMENT '所属机构' ,
    `GRADE_NAME` VARCHAR(255) NOT NULL   COMMENT '等级名称' ,
    `NEXTGRADE_ID` INTEGER NOT NULL   COMMENT '下一等级id' ,
    `IS_NEXTGRADE` INTEGER NOT NULL   COMMENT '是否有下一等级' ,
    `REQUIRED_ONBOARDINGTIME` DECIMAL(5,2) NOT NULL   COMMENT '所需入职时长' ,
    `START_SALARY` DECIMAL(5,2) NOT NULL   COMMENT '起薪' ,
    `SINGLE_SALARY` DECIMAL(5,2) NOT NULL   COMMENT '每单工资' ,
    `IS_VALID` INTEGER NOT NULL   COMMENT '是否有效' ,
    `BEGIN_TIME` TIMESTAMP NOT NULL   COMMENT '创建时间' ,
    `CHANGE_TIME` TIMESTAMP NOT NULL   COMMENT '修改时间' ,
    `DELETE_TIME` TIMESTAMP NOT NULL   COMMENT '删除时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '';


CREATE UNIQUE INDEX PRIMARY_KEY_9 ON STAFF_GRADE(ID);

DROP TABLE IF EXISTS STAFF_INFO;
CREATE TABLE STAFF_INFO(
    `ID` INTEGER NOT NULL  DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_61A71298_7D50_4570_B0C2_2F95DE86DA5B) COMMENT '主键id' ,
    `STAFF_ID` INTEGER NOT NULL   COMMENT '用户id' ,
    `PHOTO` VARCHAR(255) NOT NULL   COMMENT '照片' ,
    `JOB_ID` INTEGER NOT NULL   COMMENT '职位id' ,
    `ORIGIN` VARCHAR(255) NOT NULL   COMMENT '籍贯' ,
    `ETHNIC` VARCHAR(255) NOT NULL   COMMENT '民族' ,
    `AGE` INTEGER NOT NULL   COMMENT '年龄' ,
    `CONSTELLATION` VARCHAR(255) NOT NULL   COMMENT '星座' ,
    `DEGREE` INTEGER NOT NULL   COMMENT '学历' ,
    `WORK_EXP` INTEGER NOT NULL   COMMENT '工作经验' ,
    `MONTH_BREAK` INTEGER NOT NULL   COMMENT '每月休息' ,
    `IS_MARRIED` INTEGER NOT NULL   COMMENT '是否已婚' ,
    `ONBOARDING_STATUS` INTEGER NOT NULL   COMMENT '入职状态' ,
    `IS_FREE` INTEGER NOT NULL   COMMENT '是否空闲' ,
    `CERTIFICATE_STATUS` VARCHAR(2000) NOT NULL   COMMENT '所有证书状态' ,
    `STAFF_RANK` INTEGER NOT NULL   COMMENT '员工等级' ,
    `IS_VALID` INTEGER NOT NULL   COMMENT '是否有效' ,
    `BEGIN_TIME` TIMESTAMP NOT NULL   COMMENT '创建时间' ,
    `CHANGE_TIME` TIMESTAMP NOT NULL   COMMENT '修改时间' ,
    `DELETE_TIME` TIMESTAMP NOT NULL   COMMENT '删除时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '';


CREATE UNIQUE INDEX PRIMARY_KEY_2 ON STAFF_INFO(ID);

DROP TABLE IF EXISTS WORK;
CREATE TABLE WORK(
    `ID` INTEGER NOT NULL  DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_B1084BDB_8942_46C9_B307_523DFD2C28E8) COMMENT '主键id' ,
    `CUS_WORKNAME` VARCHAR(255) NOT NULL   COMMENT '机构名称' ,
    `CUS_WORKADRESS` VARCHAR(255) NOT NULL   COMMENT '机构地址' ,
    `CONTACT_INFOR` VARCHAR(255) NOT NULL   COMMENT '联系方式' ,
    `IS_VALID` INTEGER NOT NULL   COMMENT '是否有效' ,
    `BEGIN_TIME` TIMESTAMP NOT NULL   COMMENT '创建时间' ,
    `CHANGE_TIME` TIMESTAMP NOT NULL   COMMENT '修改时间' ,
    `DELETE_TIME` TIMESTAMP NOT NULL   COMMENT '删除时间' ,
    `CONTACT_PEOPLE` VARCHAR(255) NOT NULL   COMMENT '联系人' ,
    PRIMARY KEY (ID)
)  COMMENT = '';


CREATE UNIQUE INDEX PRIMARY_KEY_28 ON WORK(ID);

